version: '3.8'
# version: '2'

networks:
  backend:
    driver: overlay
services:
  nodeos:
    image: helixious86/eos_base_image:centos7.v1.1.1
    ports:
      - target: 8888
        published: 8888
        mode: ingress
      - target: 9000
        published: 9000
        mode: ingress
    volumes:
      - ".:/data:rw"
    environment:
      - EOSIO_CDT_VERSION=latest
      - EOS_VERSION=latest
      - SERVER_PORT=8888
      - P2P_PORT=9000
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
    working_dir: /data
    tty: true
    restart: on-failure:10
    entrypoint: bash -c "./eos_init.sh && tail -f /dev/null"
    # command: bash -c "./data/init.sh"

# enviroment variables in .env file
# EOSIO_VERSION v2.0.5
# EOSIO_CDT_VERSION v1.0
# SMART_CONTRACT_NAME tasks2
# PROJECT_PATH .
# yum install -y epel-release && yum update -y && yum install -y cmake3 git wget aptitude curl gcc gcc-c++ apt-utils && ln -s /usr/bin/cmake3 /usr/bin/cmake && ./install_deb.sh $$cdt $$eos $$contract